#cloud-config

coreos:
  update:
    reboot-strategy: "off"

  etcd2:
    name: {{ETCD_NODE_NAME}}
    initial-cluster: {{ETCD_INITIAL_CLUSTER}}
    advertise-client-urls: https://$private_ipv4:2379
    listen-client-urls: https://0.0.0.0:2379
    initial-advertise-peer-urls: https://$private_ipv4:2380
    listen-peer-urls: https://$private_ipv4:2380
    trusted-ca-file: /etc/etcd/tls/ca.pem
    peer-trusted-ca-file: /etc/etcd/tls/ca.pem
    cert-file: /etc/etcd/tls/{{IP}}-server.pem
    key-file: /etc/etcd/tls/{{IP}}-server-key.pem
    peer-cert-file: /etc/etcd/tls/{{IP}}-server.pem
    peer-key-file: /etc/etcd/tls/{{IP}}-server-key.pem

  units:

  - name: etcd2.service
    command: start

